version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "allbegray"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./storage/postgresql/data/:/var/lib/postgresql/data